name: story_teller
description: "AI powered story creator"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: 2.0.5
  json_annotation: 4.8.1
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  dio: ^5.4.0
  dart_openai: ^5.0.0
  regexpattern: ^2.6.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  firebase_crashlytics: ^3.4.9
  firebase_remote_config: ^4.3.8
  firebase_performance: ^0.9.3+8
  logger: ^2.0.2+1
  google_fonts: ^6.1.0
  easy_localization: ^3.0.3
  easy_debounce: ^2.0.3
  keyboard_dismisser: ^3.0.0
  flutter_native_splash: ^2.3.9
  flutter_onboarding_slider: ^1.0.11
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  flex_color_scheme: ^7.3.1
  gap: ^3.0.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  auto_size_text_field: ^2.2.2
  expandable: ^5.0.1
  syncfusion_flutter_sliders: 24.1.45
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  email_validator: ^2.1.17
  flutter_context_menu: ^0.1.3
  firestore_ref: ^0.14.1
  openai_dart: ^0.1.5
  flutter_dotenv: ^5.1.0
  device_info_plus: ^9.1.1
  permission_handler: ^11.2.0
  uuid: ^4.3.3
  flutter_driver:
    sdk: flutter
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.14.0
  dotted_border: ^2.1.0
  file_saver: ^0.2.9
  onesignal_flutter: ^5.0.4
  share_plus: ^7.2.1
  url_launcher: ^6.2.3
  android_intent_plus: ^4.0.3
  image: ^4.1.4
  google_mobile_ads: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  flutter_lints: ^3.0.1
  custom_lint:
  analyzer: ^5.13.0
  build_runner: ^2.4.7

analyzer:
  plugins:
    - flutter_lints

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/l10n/
    - .env