name: story_teller
description: "AI powered story creator"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  dio: ^5.4.0
  dart_openai: ^5.0.0
  regexpattern: ^2.6.0
  firebase_auth: ^4.15.2
  firebase_ui_auth: ^1.11.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.5
  firebase_crashlytics: ^3.4.8
  firebase_remote_config: ^4.3.8
  firebase_performance: ^0.9.3+8
  logger: ^2.0.2+1
  google_fonts: ^6.1.0
  easy_localization: ^3.0.3
  easy_debounce: ^2.0.3
  keyboard_dismisser: ^3.0.0
  flutter_native_splash: ^2.3.8
  flutter_onboarding_slider: ^1.0.11
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  flex_color_scheme: ^7.3.1
  gap: ^3.0.1
  auto_size_text: ^3.0.0
  get_it: ^7.6.4
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  custom_lint:
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

analyzer:
  plugins:
    - custom_lint

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/l10n/


