name: story_teller
description: "AI powered story creator"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.13.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_text_to_speech: ^2.2.0
  flutter_screenutil: ^5.9.0
  dio: ^4.0.6
  dart_openai: ^3.0.0
  regexpattern: ^2.6.0
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_storage: ^11.5.3
  firebase_crashlytics: ^3.4.6
  firebase_remote_config: ^4.3.6
  logger: ^2.0.2+1
  google_fonts: ^4.0.4
  easy_localization: ^3.0.3
  easy_debounce: ^2.0.3
  keyboard_dismisser: ^3.0.0
  flutter_native_splash: ^2.3.6
  flutter_onboarding_slider: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
